networks:
  jenkins:
    driver: bridge
services:
  jenkins_docker:
    image: docker:dind
    networks:
      jenkins:
        aliases:
          - docker # Defines to use jenkins network defined above also under the alias name `docker`.
    container_name: JenkinsDocker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    ports:
      - "2376:2376" # Exposes docker serveer port 2376 to be used by jenkins server container at "tcp://docker:2376".
    volumes:
      - ./jenkins-docker-certs:/certs/client # Docker client certs.
      - ./jenkins-data:/var/jenkins_home # Preserves Jenkins data like job definitions, credentials, build logs, etc.
      - ./extras:/extras # Any extra data or files you want to cache between server restart can be saved here `/extras/`.
  jenkins_server:
    build:
      context: .
    networks:
      - jenkins # Use jenkins network defined earlier
    container_name: JenkinsServer
    restart: always
    environment: # Define docker env variable to connect to docker-engine defined in JenkinsDocker container.
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080" # For UI
      - "50000:50000" # For API
    volumes:
      - ./jenkins-data:/var/jenkins_home:rw # Docker client certs.
      - ./jenkins-docker-certs:/certs/client:ro # Preserves Jenkins data like job definitions, credentials, build logs, etc.
      - ./extras:/extras:rw # Any extra data or files you want to cache between server restart can be saved here `/extras/`.
  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    expose:   
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3XSRcGxy3ilDUZIkf6iCVjHZ0eb9+qhKH2pWpJ3WmUlVDGbs3Bk8MX8lQzUhuRgm2eDYAkpKAgiOEVDqG50QVjh9TIOBSTAttlfvMNmm45igjjTBMVrYqEVpabiTvNDoJqKErwCq/mulQ6ncIxCgucb6WQLToQGBA3KPwitXvHGddTn1KYpqx3G9ThgY5Sj7BmC1TG2d4vPAf/d828jLXv9Mo7k7UKscmpnMxh76PKx0YvNEUoTw7qutQzfaH3EPDPPspHMAXkEbpHzsWHFf4vfEAR+lRd0CwvrxcCx+BPm+5hsD/pwhFDwXQ7NOyYIReLXU4BcugVCZFOd/5SMtrMKexAL3y5PhD+O3J4VnF5waKLuG1qDZp0G0Ajf3mftbIGagF1TO8cbyzMad/U5+TwfuWAnmKif2N62r25e1ZbQTgpGOd3rSBHzi1aN3pwO0cf/xuorvGEG30PKUTDGJfedvC6arSSTHB5bTissXY/5jQmIXBLU00vTgzUZi2WTM= devalore@DESKTOP-KNVAS7I
  nexus:
    image: sonatype/nexus
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
  
volumes:
  nexus-data: {}      
